export const PRODUCT_REQUEST='PRODUCT_REQUEST'
export const PRODUCT_SUCCESS='PRODUCT_SUCCESS'
export const PRODUCT_FAILURE='PRODUCT_FAILURE'

export const CATEGORY_REQUEST='CATEGORY_REQUEST'
export const CATEGORY_SUCCESS='CATEGORY_SUCCESS'
export const CATEGORY_FAILURE='CATEGORY_FAILURE'

export const PARTICULAR_REQUEST='PARTICULAR_REQUEST'
export const PARTICULAR_SUCCESS='PARTICULAR_SUCCESS'
export const PARTICULAR_FAILURE='PARTICULAR_FAILURE'

export const ADD_CART_REQUEST='ADD_CART_REQUEST'
export const ADD_CART_SUCCESS='ADD_CART_SUCCESS'
export const ADD_CART_FAILURE='ADD_CART_FAILURE'

export const CART_REQUEST='CART_REQUEST'
export const CART_SUCCESS='CART_SUCCESS'
export const CART_FAILURE='CART_FAILURE'

export const INC_REQUEST='INC_REQUEST'
export const INC_SUCCESS='INC_SUCCESS'
export const INC_FAILURE='INC_FAILURE'

export const DEC_REQUEST='DEC_REQUEST'
export const DEC_SUCCESS='DEC_SUCCESS'
export const DEC_FAILURE='DEC_FAILURE'