export const PRODUCT_REQUEST='PRODUCT_REQUEST'
export const PRODUCT_SUCCESS='PRODUCT_SUCCESS'
export const PRODUCT_FAILURE='PRODUCT_FAILURE'

export const CATEGORY_REQUEST='CATEGORY_REQUEST'
export const CATEGORY_SUCCESS='CATEGORY_SUCCESS'
export const CATEGORY_FAILURE='CATEGORY_FAILURE'

export const PARTICULAR_REQUEST='PARTICULAR_REQUEST'
export const PARTICULAR_SUCCESS='PARTICULAR_SUCCESS'
export const PARTICULAR_FAILURE='PARTICULAR_FAILURE'